export const STATES_BY_TYPE = {
    VOLUMEN:       ['ENCENDIDO', 'APAGADO', 'MANTENIMIENTO'],
    PRESION:       ['ENCENDIDO', 'APAGADO', 'MANTENIMIENTO'],
    CAUDAL:        ['ENCENDIDO', 'APAGADO', 'MANTENIMIENTO'],
    HUMEDAD:       ['ENCENDIDO', 'APAGADO', 'MANTENIMIENTO'],
    PULSADOR:      ['ACTIVO',    'INACTIVO', 'MANTENIMIENTO'],
    BOMBA:         ['ENCENDIDO', 'APAGADO', 'MANTENIMIENTO', ],
    ELECTROVALVULA:['ABIERTO',   'CERRADO',  'MANTENIMIENTO']
};